apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium
  template:
    metadata:
      labels:
        app: selenium
    spec:
      containers:
        - name: selenium
          image: vaishnavikarra869/selenium:v1
          ports:
            - containerPort: 5001
