apiVersion: v1
kind: Service
metadata:
  name: seleniumtestdemoapp-service
spec:
  selector:
    app: seleniumtestdemoapp
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30189
  type: NodePort
